apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: g3xb126fx-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-da59406f64.v2u2.p3.openshiftapps.com/rhtap/rhtap-qe:7b7e4234edc55094275b2e129c9ea2d78e67f935@sha256:d290c5af3c9db8769c4974f00ca4b248d2ec95510be4daa83e6f25f8e9e4d814
          name: container-image
